project:
  type: website
  output-dir: docs

website:
  title: "ARCH7476: Evidence-Based Generative Design"
  navbar:
    logo: "assets/ARCH7476_HONGSHAN GUO.pdf"
    left:
      - href: index.qmd
        text: Home
      - href: schedule.qmd
        text: Schedule
      - href: assignments.qmd
        text: Assignments
      - href: resources.qmd
        text: Resources
    right:
      - icon: github
        href: https://github.com/
        aria-label: GitHub
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Course Overview"
        contents:
          - index.qmd
          - schedule.qmd
      - section: "Assignments"
        contents:
          - assignments.qmd
          - text: "A1: Decision Claim"
            href: assignments/assignment-01.qmd
          - text: "A2: Evidence Map"
            href: assignments/assignment-02.qmd
          - text: "A3: Test Plan + Pilot"
            href: assignments/assignment-03.qmd
          - text: "A4: Final Package"
            href: assignments/assignment-04.qmd
      - section: "Resources"
        contents:
          - resources.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 3
    code-fold: false
    code-tools: true

execute:
  freeze: auto
  cache: true