project:
  type: website
  output-dir: docs

website:
  title: "ARCH7476: Evidence-Based Generative Design"
  navbar:
    logo: "assets/ARCH7476_HONGSHAN GUO.pdf"
    left:
      - href: index.qmd
        text: Home
      - href: schedule.qmd
        text: Schedule
      - href: assignments.qmd
        text: Assignments
      - href: resources.qmd
        text: Resources
    right:
      - icon: github
        href: https://github.com/
        aria-label: GitHub
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Course Overview"
        contents:
          - index.qmd
          - schedule.qmd
      - section: "Weekly Content"
        contents:
          - text: "W1: Why Evidence Matters"
            href: weeks/week-01.qmd
          - text: "W2: Finding and Framing Data"
            href: weeks/week-02.qmd
          - text: "W3: Planning a Test"
            href: weeks/week-03.qmd
          - text: "W4: Sensitivity & Peer Check"
            href: weeks/week-04.qmd
          - text: "W5: Pilot Week"
            href: weeks/week-05.qmd
          - text: "W6: Making Results Readable"
            href: weeks/week-06.qmd
          - text: "W7: Decide with Numbers"
            href: weeks/week-07.qmd
          - text: "W8: Light Workflow Help"
            href: weeks/week-08.qmd
          - text: "W9: Storytelling & Figures"
            href: weeks/week-09.qmd
          - text: "W10: Draft Defense"
            href: weeks/week-10.qmd
          - text: "W11: Final Polish"
            href: weeks/week-11.qmd
          - text: "W12: Object Fair"
            href: weeks/week-12.qmd
      - section: "Assignments"
        contents:
          - assignments.qmd
          - text: "A1: Decision Claim"
            href: assignments/assignment-01.qmd
          - text: "A2: Evidence Map"
            href: assignments/assignment-02.qmd
          - text: "A3: Test Plan + Pilot"
            href: assignments/assignment-03.qmd
          - text: "A4: Final Package"
            href: assignments/assignment-04.qmd
      - section: "Resources"
        contents:
          - resources.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 3
    code-fold: false
    code-tools: true

execute:
  freeze: auto
  cache: true